/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProfitabilityRouteImport } from './routes/profitability'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HitachiRouteImport } from './routes/hitachi'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as CompaniesRouteImport } from './routes/companies'
import { Route as CashbookRouteImport } from './routes/cashbook'
import { Route as BillsRouteImport } from './routes/bills'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompaniesIndexRouteImport } from './routes/companies.index'
import { Route as ReportsBackdatedRouteImport } from './routes/reports.backdated'
import { Route as CompaniesIdRouteImport } from './routes/companies.$id'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfitabilityRoute = ProfitabilityRouteImport.update({
  id: '/profitability',
  path: '/profitability',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HitachiRoute = HitachiRouteImport.update({
  id: '/hitachi',
  path: '/hitachi',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const CashbookRoute = CashbookRouteImport.update({
  id: '/cashbook',
  path: '/cashbook',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsRoute = BillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesIndexRoute = CompaniesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CompaniesRoute,
} as any)
const ReportsBackdatedRoute = ReportsBackdatedRouteImport.update({
  id: '/backdated',
  path: '/backdated',
  getParentRoute: () => ReportsRoute,
} as any)
const CompaniesIdRoute = CompaniesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CompaniesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/bills': typeof BillsRoute
  '/cashbook': typeof CashbookRoute
  '/companies': typeof CompaniesRouteWithChildren
  '/expenses': typeof ExpensesRoute
  '/hitachi': typeof HitachiRoute
  '/login': typeof LoginRoute
  '/products': typeof ProductsRoute
  '/profitability': typeof ProfitabilityRoute
  '/reports': typeof ReportsRouteWithChildren
  '/signup': typeof SignupRoute
  '/trust': typeof TrustRoute
  '/users': typeof UsersRoute
  '/companies/$id': typeof CompaniesIdRoute
  '/reports/backdated': typeof ReportsBackdatedRoute
  '/companies/': typeof CompaniesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/bills': typeof BillsRoute
  '/cashbook': typeof CashbookRoute
  '/expenses': typeof ExpensesRoute
  '/hitachi': typeof HitachiRoute
  '/login': typeof LoginRoute
  '/products': typeof ProductsRoute
  '/profitability': typeof ProfitabilityRoute
  '/reports': typeof ReportsRouteWithChildren
  '/signup': typeof SignupRoute
  '/trust': typeof TrustRoute
  '/users': typeof UsersRoute
  '/companies/$id': typeof CompaniesIdRoute
  '/reports/backdated': typeof ReportsBackdatedRoute
  '/companies': typeof CompaniesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/bills': typeof BillsRoute
  '/cashbook': typeof CashbookRoute
  '/companies': typeof CompaniesRouteWithChildren
  '/expenses': typeof ExpensesRoute
  '/hitachi': typeof HitachiRoute
  '/login': typeof LoginRoute
  '/products': typeof ProductsRoute
  '/profitability': typeof ProfitabilityRoute
  '/reports': typeof ReportsRouteWithChildren
  '/signup': typeof SignupRoute
  '/trust': typeof TrustRoute
  '/users': typeof UsersRoute
  '/companies/$id': typeof CompaniesIdRoute
  '/reports/backdated': typeof ReportsBackdatedRoute
  '/companies/': typeof CompaniesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/billing'
    | '/bills'
    | '/cashbook'
    | '/companies'
    | '/expenses'
    | '/hitachi'
    | '/login'
    | '/products'
    | '/profitability'
    | '/reports'
    | '/signup'
    | '/trust'
    | '/users'
    | '/companies/$id'
    | '/reports/backdated'
    | '/companies/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/billing'
    | '/bills'
    | '/cashbook'
    | '/expenses'
    | '/hitachi'
    | '/login'
    | '/products'
    | '/profitability'
    | '/reports'
    | '/signup'
    | '/trust'
    | '/users'
    | '/companies/$id'
    | '/reports/backdated'
    | '/companies'
  id:
    | '__root__'
    | '/'
    | '/billing'
    | '/bills'
    | '/cashbook'
    | '/companies'
    | '/expenses'
    | '/hitachi'
    | '/login'
    | '/products'
    | '/profitability'
    | '/reports'
    | '/signup'
    | '/trust'
    | '/users'
    | '/companies/$id'
    | '/reports/backdated'
    | '/companies/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BillingRoute: typeof BillingRoute
  BillsRoute: typeof BillsRoute
  CashbookRoute: typeof CashbookRoute
  CompaniesRoute: typeof CompaniesRouteWithChildren
  ExpensesRoute: typeof ExpensesRoute
  HitachiRoute: typeof HitachiRoute
  LoginRoute: typeof LoginRoute
  ProductsRoute: typeof ProductsRoute
  ProfitabilityRoute: typeof ProfitabilityRoute
  ReportsRoute: typeof ReportsRouteWithChildren
  SignupRoute: typeof SignupRoute
  TrustRoute: typeof TrustRoute
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profitability': {
      id: '/profitability'
      path: '/profitability'
      fullPath: '/profitability'
      preLoaderRoute: typeof ProfitabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hitachi': {
      id: '/hitachi'
      path: '/hitachi'
      fullPath: '/hitachi'
      preLoaderRoute: typeof HitachiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cashbook': {
      id: '/cashbook'
      path: '/cashbook'
      fullPath: '/cashbook'
      preLoaderRoute: typeof CashbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills': {
      id: '/bills'
      path: '/bills'
      fullPath: '/bills'
      preLoaderRoute: typeof BillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/': {
      id: '/companies/'
      path: '/'
      fullPath: '/companies/'
      preLoaderRoute: typeof CompaniesIndexRouteImport
      parentRoute: typeof CompaniesRoute
    }
    '/reports/backdated': {
      id: '/reports/backdated'
      path: '/backdated'
      fullPath: '/reports/backdated'
      preLoaderRoute: typeof ReportsBackdatedRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/companies/$id': {
      id: '/companies/$id'
      path: '/$id'
      fullPath: '/companies/$id'
      preLoaderRoute: typeof CompaniesIdRouteImport
      parentRoute: typeof CompaniesRoute
    }
  }
}

interface CompaniesRouteChildren {
  CompaniesIdRoute: typeof CompaniesIdRoute
  CompaniesIndexRoute: typeof CompaniesIndexRoute
}

const CompaniesRouteChildren: CompaniesRouteChildren = {
  CompaniesIdRoute: CompaniesIdRoute,
  CompaniesIndexRoute: CompaniesIndexRoute,
}

const CompaniesRouteWithChildren = CompaniesRoute._addFileChildren(
  CompaniesRouteChildren,
)

interface ReportsRouteChildren {
  ReportsBackdatedRoute: typeof ReportsBackdatedRoute
}

const ReportsRouteChildren: ReportsRouteChildren = {
  ReportsBackdatedRoute: ReportsBackdatedRoute,
}

const ReportsRouteWithChildren =
  ReportsRoute._addFileChildren(ReportsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BillingRoute: BillingRoute,
  BillsRoute: BillsRoute,
  CashbookRoute: CashbookRoute,
  CompaniesRoute: CompaniesRouteWithChildren,
  ExpensesRoute: ExpensesRoute,
  HitachiRoute: HitachiRoute,
  LoginRoute: LoginRoute,
  ProductsRoute: ProductsRoute,
  ProfitabilityRoute: ProfitabilityRoute,
  ReportsRoute: ReportsRouteWithChildren,
  SignupRoute: SignupRoute,
  TrustRoute: TrustRoute,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
