/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as JcbRouteImport } from './routes/jcb'
import { Route as HitachiRouteImport } from './routes/hitachi'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as CompaniesRouteImport } from './routes/companies'
import { Route as BillsRouteImport } from './routes/bills'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as IndexRouteImport } from './routes/index'

const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const JcbRoute = JcbRouteImport.update({
  id: '/jcb',
  path: '/jcb',
  getParentRoute: () => rootRouteImport,
} as any)
const HitachiRoute = HitachiRouteImport.update({
  id: '/hitachi',
  path: '/hitachi',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsRoute = BillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/bills': typeof BillsRoute
  '/companies': typeof CompaniesRoute
  '/customers': typeof CustomersRoute
  '/expenses': typeof ExpensesRoute
  '/hitachi': typeof HitachiRoute
  '/jcb': typeof JcbRoute
  '/products': typeof ProductsRoute
  '/reports': typeof ReportsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/bills': typeof BillsRoute
  '/companies': typeof CompaniesRoute
  '/customers': typeof CustomersRoute
  '/expenses': typeof ExpensesRoute
  '/hitachi': typeof HitachiRoute
  '/jcb': typeof JcbRoute
  '/products': typeof ProductsRoute
  '/reports': typeof ReportsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/bills': typeof BillsRoute
  '/companies': typeof CompaniesRoute
  '/customers': typeof CustomersRoute
  '/expenses': typeof ExpensesRoute
  '/hitachi': typeof HitachiRoute
  '/jcb': typeof JcbRoute
  '/products': typeof ProductsRoute
  '/reports': typeof ReportsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/billing'
    | '/bills'
    | '/companies'
    | '/customers'
    | '/expenses'
    | '/hitachi'
    | '/jcb'
    | '/products'
    | '/reports'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/billing'
    | '/bills'
    | '/companies'
    | '/customers'
    | '/expenses'
    | '/hitachi'
    | '/jcb'
    | '/products'
    | '/reports'
  id:
    | '__root__'
    | '/'
    | '/billing'
    | '/bills'
    | '/companies'
    | '/customers'
    | '/expenses'
    | '/hitachi'
    | '/jcb'
    | '/products'
    | '/reports'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BillingRoute: typeof BillingRoute
  BillsRoute: typeof BillsRoute
  CompaniesRoute: typeof CompaniesRoute
  CustomersRoute: typeof CustomersRoute
  ExpensesRoute: typeof ExpensesRoute
  HitachiRoute: typeof HitachiRoute
  JcbRoute: typeof JcbRoute
  ProductsRoute: typeof ProductsRoute
  ReportsRoute: typeof ReportsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jcb': {
      id: '/jcb'
      path: '/jcb'
      fullPath: '/jcb'
      preLoaderRoute: typeof JcbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hitachi': {
      id: '/hitachi'
      path: '/hitachi'
      fullPath: '/hitachi'
      preLoaderRoute: typeof HitachiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills': {
      id: '/bills'
      path: '/bills'
      fullPath: '/bills'
      preLoaderRoute: typeof BillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BillingRoute: BillingRoute,
  BillsRoute: BillsRoute,
  CompaniesRoute: CompaniesRoute,
  CustomersRoute: CustomersRoute,
  ExpensesRoute: ExpensesRoute,
  HitachiRoute: HitachiRoute,
  JcbRoute: JcbRoute,
  ProductsRoute: ProductsRoute,
  ReportsRoute: ReportsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
